import './helpers'
import './directives'
import './axios'
import './fontawesome'
// import './lightbox' // un-comment if using viewer lightbox plugin
import './vtooltip'
import './vuelidate'
import './vnotifications'
import './multiselect'
import './draggable'
import './contentLoader'
import './datePicker'
import './moment'
// import './vformWizard' // un-comment if using form wizard/stepper plugin
import './scrollTo'
import './vmodal'
import './togglebutton'
import './bootstrap'
import 'bootstrap'
